### ISSUE TITLE
Generator Idea: The ability to share sliders

### ISSUE THREAD

**Issue by nathan815** [CodyL19/CanLoad.js#2]
I think it would be cool if you could share a link to a slider made with the generator.

This could be done with a hash added at the end of the URL like:

```
http://codyl19.github.io/CanLoad.js/#style=chrome&speed=fast&color=0,162,250&size=40&line=10&length=1
```

Just an idea :)

**Comment by CodyL19** [comment]
Good idea!

**Comment by CodyL19** [comment]
Done! http://codyl19.github.io/CanLoad.js/#st=chrome&c=71,71,71,1&sp=Medium&bg=71,71,71,1&s=60&l=21&len=72&bgc=60,182,221,1&bgl=28
